### PR TITLE
Migrating to GitHub actions

### LINKED ISSUE #35: Move CI from travis -> actions
The current CI tests haven't been running because we were using Travis (RIP). We need to figure out how to install various MPI implementations on GitHub actions and run the tests there.

cc @dfm

### PR DESCRIPTION
**Pull request by dfm**
Closes #35

### CODE REVIEW

**Comment by dfm** [comment]
@adrn: If https://github.com/dfm/schwimmbad/actions/runs/599840483 passes then I'll remove the one `FIXME` and this should be good to go.

Except perhaps we should fix the badges etc as part of this PR?

**Comment by adrn** [comment]
🎉 Thanks! This is rad -- I really appreciate it! It looks like that passed, so I'd be happy to merge. If you want to update the badges, go for it, but also happy to do that in a follow-up commit :)

**Comment by dfm** [comment]
no problem! There was an issue with the coverage: let me make sure I fixed it and then it'll be good to go. Let's do the badges in a follow-up.

**Comment by dfm** [comment]
OK - I merged. Let me know if there are any issues!

**Pull request merged**
